[workspace]
members = [
    "consumer",
    "zksync_error",
]
resolver = "2"

[workspace.package]
authors = [
    "Igor Zhirkov <iz@matterlabs.dev>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
version = "0.1.0"

